variables:
  ArtifactName: 'PurpleTechnology.Common.Utils'
  buildConfiguration: "Release"
  BuildProject: '$(ArtifactName)/$(ArtifactName).csproj'
  PackagesToPack: '$(BuildProject)'
  PackDirectory: '$(Build.ArtifactStagingDirectory)/$(ArtifacName)'
  BuildArguments: '--configuration $(buildConfiguration) --framework netstandard2.1 --verbosity detailed'
  PathtoPublish: '$(PackDirectory)'

name: '$(GITVERSION_SemVer)'

trigger:
- master
- feature/*

pr:
- master
- feature/*

pool:
  vmImage: 'windows-latest'

steps:

- task: GitVersion@5
  inputs:
    runtime: 'core'
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  displayName: 'Build runtime library'
  inputs:
    command: build
    arguments: '$(BuildArguments)'
    projects: '$(BuildProject)'
#    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'Pack nuget package'
  inputs:
    command: 'pack'
    packagesToPack: '$(PackagesToPack)'
    packDirectory: '$(PackDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.NuGetVersion'
#    arguments: '$(BuildArguments)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(PathtoPublish)'
    ArtifactName: '$(ArtifactName)'
    parallel: true

- task: DotNetCoreCLI@2
  displayName: 'Publish nuget package to the feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    feedPublish: 'Putech'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

