variables:
  BuildArguments: '--configuration Release --framework netstandard2.1 -maxcpucount --verbosity detailed'

name: '$(GITVERSION_SemVer)'

trigger:
- master
- feature/*

pr:
- master
- feature/*

pool:
  vmImage: 'windows-latest'

steps:

- task: GitVersion@5
  inputs:
    runtime: 'core'
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  displayName: 'Build runtime library'
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: 'Pack nuget package'
  inputs:
    command: 'pack'
    includesymbols: true
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.NuGetVersion'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: PurpleTechnology.Common.Utils
    parallel: true

